[phases.setup]
# We must include python311 because defining this list overrides the defaults.
# We add xorg.libxcb and others to satisfy the "full" OpenCV.
nixPkgs = ["python311", "ffmpeg", "glib", "xorg.libxcb", "libGL", "xorg.libX11", "xorg.libXext", "xorg.libXrender"]

[variables]
PYTHONUNBUFFERED = "1"
