[phases.setup]
# We explicitly add Python 3.11 and the missing system libraries
nixPkgs = [
    "python311",
    "ffmpeg",
    "glib",
    "xorg.libxcb",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender",
    "libGL"
]

[variables]
PYTHONUNBUFFERED = "1"
